Transcriptor factor evaluation

In [1]:
import scanpy as sc
import decoupler as dc

# Only needed for processing
import numpy as np
import pandas as pd
from anndata import AnnData

In [2]:
import pandas as pd
import yaml

In [3]:
dds_files_path = '../data/dds_files.yml'

In [5]:
with open(dds_files_path, 'r') as file:
    dds_dict = yaml.safe_load(file)

In [7]:
mat_dict = {}
for dds, file in dds_dict.items():
    mat = pd.read_csv(file, index_col=0)[['stat']].T.rename(index={'stat': dds})
    mat.T.to_csv(f'results/mat_{dds}.csv')
    mat_dict[dds]=mat.copy()

In [8]:
collectri = pd.read_csv('collectri.csv')

In [9]:
len(collectri['target'].unique())

6692

In [10]:
mat_dict['yo_file']

,TSPAN6,TNMD,DPM1,SCYL3,FIRRM,FGR,CFH,FUCA2,GCLC,NFYA,...,Unnamed: 34318,Unnamed: 34319,PDGFRL2P,POLR2J3.1,Unnamed: 34322,C4orf36.1,Unnamed: 34327,H2BK1,Unnamed: 34332,TBCEL-TECTA
yo_file,-0.373394,-0.305723,-0.92296,-2.114769,-2.256718,-0.22918,-3.591853,-1.408615,-2.504045,-2.09685,...,-0.061354,-1.754382,0.38343,-0.101156,0.174517,-1.591932,-0.072975,0.009957,1.347965,0.490102

In [12]:
test = 'MTSS1'
collectri[(collectri['source']==test) | (collectri['target']==test)]

       Unnamed: 0  source target  weight      PMID
21037       21037  DNMT3B  MTSS1       1  21909138
29540       29540   NR1I2  MTSS1       1  19129222
36480       36480    TBX5  MTSS1       1  20802524

In [21]:
# Infer TF activities with ulm
tf_dict = {}
for comparison, mat in mat_dict.items():
    comparison = comparison[:-5]
    tf_dict[comparison] = dc.run_ulm(mat=mat, net=collectri, verbose=True) # tf_acts, tf_pvals
    tf_acts=tf_dict[comparison][0]
    tf_pvals = tf_dict[comparison][1]
    tf_df = pd.DataFrame(tf_acts.T)
    tf_df['pvals']=tf_pvals.T
    tf_df.to_csv(f'results/tf_acts_{comparison}.csv')
    tf_df

2 features of mat are empty, they will be removed.
Running ulm on mat with 1 samples and 25376 targets for 759 sources.
Running ulm on mat with 1 samples and 25378 targets for 759 sources.
Running ulm on mat with 1 samples and 25378 targets for 759 sources.
13 features of mat are empty, they will be removed.
Running ulm on mat with 1 samples and 32739 targets for 771 sources.
Running ulm on mat with 1 samples and 20419 targets for 721 sources.
12 features of mat are empty, they will be removed.
Running ulm on mat with 1 samples and 32740 targets for 771 sources.
Running ulm on mat with 1 samples and 20419 targets for 721 sources.
12 features of mat are empty, they will be removed.
Running ulm on mat with 1 samples and 32740 targets for 771 sources.
Running ulm on mat with 1 samples and 20419 targets for 721 sources.
Running ulm on mat with 1 samples and 17977 targets for 718 sources.
Running ulm on mat with 1 samples and 21574 targets for 719 sources.
108 features of mat are empty, they will be removed.
Running ulm on mat with 1 samples and 32777 targets for 773 sources.

         mf_o_file     pvals
ABL1      0.579483  0.562268
AHR       0.111940  0.910872
AHRR      0.134061  0.893355
AIP       0.345107  0.730016
AIRE      0.511664  0.608890
...            ...       ...
ZNF699    0.695029  0.487042
ZNF76     0.159859  0.872993
ZNF804A   1.580250  0.114059
ZNF91     1.437023  0.150721
ZXDC      1.924274  0.054329

[773 rows x 2 columns]

In [18]:
tf_dict['yo_file'][0]

,ABL1,AHR,AHRR,AIP,AIRE,APEX1,AR,ARID1A,ARID1B,ARID3A,...,ZNF382,ZNF384,ZNF395,ZNF410,ZNF436,ZNF699,ZNF76,ZNF804A,ZNF91,ZXDC
yo_file,-1.80901,-0.834095,-1.40623,1.878036,-0.690838,-0.303316,0.465972,0.205746,-0.895146,-2.187568,...,1.992351,0.925196,-0.105874,-0.011511,0.02725,0.144145,0.262173,0.395323,0.81695,-0.269214

In [19]:
tf_dict['yo_file'][1]

,ABL1,AHR,AHRR,AIP,AIRE,APEX1,AR,ARID1A,ARID1B,ARID3A,...,ZNF382,ZNF384,ZNF395,ZNF410,ZNF436,ZNF699,ZNF76,ZNF804A,ZNF91,ZXDC
yo_file,0.070461,0.404235,0.159668,0.060388,0.489674,0.761652,0.641239,0.836991,0.370718,0.02871,...,0.046343,0.354873,0.915683,0.990816,0.978261,0.885387,0.793191,0.692608,0.413965,0.787767