# Get the pathways of the selected genes
this is the inverse of the pathway analysis, I want to have a list of genes and add what are the pathways that are register for that gene

In [1]:
import scanpy as sc
import decoupler as dc

# Only needed for processing
import numpy as np
import pandas as pd
from upsetplot import generate_counts
from upsetplot import plot
from matplotlib import pyplot
from upsetplot import from_memberships
from upsetplot import from_contents

In [3]:
msigdb = pd.read_csv('../msigdb.csv')

In [20]:
sel_db = ['go_molecular_function',
                                  'go_cellular_component',
                                  'go_biological_process',
                                  'reactome_pathways',
                                  'kegg_pathways', 'hallmark']

In [11]:
msigdb.head()

,Unnamed: 0,genesymbol,collection,geneset
0,0,MAFF,chemical_and_genetic_perturbations,BOYAULT_LIVER_CANCER_SUBCLASS_G56_DN
1,1,MAFF,chemical_and_genetic_perturbations,ELVIDGE_HYPOXIA_UP
2,2,MAFF,chemical_and_genetic_perturbations,NUYTTEN_NIPP1_TARGETS_DN
3,3,MAFF,immunesigdb,GSE17721_POLYIC_VS_GARDIQUIMOD_4H_BMDC_DN
4,4,MAFF,chemical_and_genetic_perturbations,SCHAEFFER_PROSTATE_DEVELOPMENT_12HR_UP

In [19]:
msigdb['collection'].unique()

array(['chemical_and_genetic_perturbations', 'immunesigdb',
       'mirna_targets_mirdb', 'go_molecular_function', 'tf_targets_gtrf',
       'tf_targets_legacy', 'oncogenic_signatures',
       'cell_type_signatures', 'vaccine_response',
       'go_biological_process', 'cancer_gene_neighborhoods',
       'cancer_modules', 'go_cellular_component', 'wikipathways',
       'reactome_pathways', 'hallmark', 'mirna_targets_legacy',
       'biocarta_pathways', 'positional', 'human_phenotype_ontology',
       'pid_pathways', 'kegg_pathways'], dtype=object)

In [22]:
msigdb_filter =msigdb[msigdb['collection'].isin(sel_db)]

In [35]:
msigdb_immune =msigdb[msigdb['collection']=='immunesigdb']
msigdb_immune = msigdb_immune[~msigdb_immune['geneset'].str.contains('GSE')]
msigdb_immune[~msigdb_immune['geneset'].str.contains('_VS_')]

Empty DataFrame
Columns: [Unnamed: 0, genesymbol, collection, geneset]
Index: []

In [6]:
gene_df = pd.read_csv("ortholog_selected_genes_sources.csv", index_col=0)

In [10]:
gene_df= gene_df[gene_df["caenorhabditis_elegans"].notna() & (gene_df["caenorhabditis_elegans"] != "")& (gene_df["caenorhabditis_elegans"] != " ")]
len(gene_df)

57

In [ ]:
geneset_dict = msigdb_filter.groupby("genesymbol")["geneset"].apply(list).to_dict()
geneset_dict

In [ ]:

# Add a new column 'Pathways' to merged_df by mapping genesymbol to genesets
gene_df["Pathways"] = gene_df["human"].map(geneset_dict)

gene_df

In [32]:
gene_df["n_Pathways"] = [len(p) if isinstance(p, list) else 0 for p in gene_df["Pathways"]]
gene_df.head()

,Ensembl,Shap/tstat,Source,LFC,Best,gorilla_gorilla,saccharomyces_cerevisiae,caenorhabditis_elegans,mus_musculus,pongo_abelii,human,Pathways,n_Pathways
Symbol,,,,,,,,,,,,,
NT5C2,ENSG00000076685.18,14.135628,Catboost 07,NaN,1.0,,,Y71H10B.1,Nt5c2,NT5C2,NT5C2,[GOBP_RIBONUCLEOSIDE_MONOPHOSPHATE_CATABOLIC_P...,57
ALDOA,ENSG00000285043.1,7.641741,Catboost 07,NaN,4.0,,,aldo-1,Aldoart1,,ALDOA,[GOBP_RIBONUCLEOSIDE_DIPHOSPHATE_METABOLIC_PRO...,103
BLCAP,ENSG00000166619.12,3.897527,Catboost 07,NaN,8.0,,,Y73E7A.6,Blcap,BLCAP,BLCAP,"[GOBP_APOPTOTIC_PROCESS, GOBP_CELLULAR_COMPONE...",6
FEZ2,ENSG00000171055.14,2.825766,Catboost 07,NaN,9.0,,,unc-76,Fez2,FEZ2,FEZ2,"[GOBP_TAXIS, GOBP_AUTOPHAGOSOME_ORGANIZATION, ...",35
SLC16A3,ENSG00000141526.16,1.558696,Catboost 07,NaN,13.0,,MCH5,mct-3,Slc16a3,SLC16A3,SLC16A3,"[GOCC_POSTSYNAPTIC_MEMBRANE, REACTOME_THE_CITR...",67

In [39]:
inmunne_gene_list=[]
with open("inmune_genes_symbol.txt", 'r') as file:
      inmunne_gene_list = [line.strip() for line in file]

In [40]:
gene_df["immune_gene"] = ['immune' if g in inmunne_gene_list else '' for g in gene_df.index]

In [41]:
gene_df

,Ensembl,Shap/tstat,Source,LFC,Best,gorilla_gorilla,saccharomyces_cerevisiae,caenorhabditis_elegans,mus_musculus,pongo_abelii,human,Pathways,n_Pathways,immune_gene
Symbol,,,,,,,,,,,,,,
NT5C2,ENSG00000076685.18,14.135628,Catboost 07,NaN,1.0,,,Y71H10B.1,Nt5c2,NT5C2,NT5C2,[GOBP_RIBONUCLEOSIDE_MONOPHOSPHATE_CATABOLIC_P...,57,
ALDOA,ENSG00000285043.1,7.641741,Catboost 07,NaN,4.0,,,aldo-1,Aldoart1,,ALDOA,[GOBP_RIBONUCLEOSIDE_DIPHOSPHATE_METABOLIC_PRO...,103,immune
BLCAP,ENSG00000166619.12,3.897527,Catboost 07,NaN,8.0,,,Y73E7A.6,Blcap,BLCAP,BLCAP,"[GOBP_APOPTOTIC_PROCESS, GOBP_CELLULAR_COMPONE...",6,
FEZ2,ENSG00000171055.14,2.825766,Catboost 07,NaN,9.0,,,unc-76,Fez2,FEZ2,FEZ2,"[GOBP_TAXIS, GOBP_AUTOPHAGOSOME_ORGANIZATION, ...",35,
SLC16A3,ENSG00000141526.16,1.558696,Catboost 07,NaN,13.0,,MCH5,mct-3,Slc16a3,SLC16A3,SLC16A3,"[GOCC_POSTSYNAPTIC_MEMBRANE, REACTOME_THE_CITR...",67,
STUM,ENSG00000203685.9,1.490482,Catboost 07,NaN,14.0,,,Y51H7BR.7,Stum,STUM,STUM,NaN,0,
STUM,ENSG00000203685.9,19.534839,Catboost 40,NaN,1.0,,,Y51H7BR.7,Stum,STUM,STUM,NaN,0,
CA3,ENSG00000164879.6,4.181707,Catboost 40,NaN,5.0,,,cah-6,Car3,CA3,CA3,"[GOMF_PHOSPHATASE_ACTIVITY, GOMF_CARBON_OXYGEN...",17,
STIM1,ENSG00000167323.11,3.817382,Catboost 40,NaN,6.0,,,stim-1,Stim1,STIM1,STIM1,"[GOBP_CHEMICAL_HOMEOSTASIS, GOBP_REGULATION_OF...",109,immune
ACIN1,ENSG00000100813.14,2.817629,Catboost 40,NaN,7.0,,,acin-1,Acin1,ACIN1,ACIN1,"[GOBP_MRNA_METABOLIC_PROCESS, GOBP_POSITIVE_RE...",54,
HNRNPM,ENSG00000099783.11,2.654109,Catboost 40,NaN,8.0,,HRB1,sup-46,Hnrnpm,,HNRNPM,"[REACTOME_SIGNALING_BY_FGFR, GOBP_MRNA_METABOL...",29,immune
TPM3,ENSG00000143549.19,6.835912,Ridge 40,NaN,2.0,,,lev-11,Tpm3-rs7,,TPM3,"[REACTOME_STRIATED_MUSCLE_CONTRACTION, GOCC_AC...",34,
CALM1,ENSG00000198668.10,5.917629,Ridge 40,NaN,4.0,,,cal-1,Calm1,CALM1,CALM1,"[REACTOME_CALCINEURIN_ACTIVATES_NFAT, GOBP_NEG...",352,immune
EHMT1,ENSG00000181090.20,5.451860,Ridge 40,NaN,5.0,,,set-13,Ehmt1,EHMT1,EHMT1,"[GOMF_TRANSCRIPTION_COREPRESSOR_BINDING, GOMF_...",73,
MYL2,ENSG00000111245.14,5.233951,Ridge 40,NaN,8.0,,,mlc-1,Myl2,Symbol not found,MYL2,"[GOBP_MUSCLE_ORGAN_MORPHOGENESIS, REACTOME_STR...",82,
RPS24,ENSG00000138326.19,5.029357,Ridge 40,NaN,9.0,,RPS24B,T07A9.14,,,RPS24,"[GOBP_CYTOPLASMIC_TRANSLATION, REACTOME_EUKARY...",57,
ENO3,ENSG00000108515.17,4.999977,Ridge 40,NaN,10.0,,ERR3,enol-1,Eno3,,ENO3,[GOBP_RIBONUCLEOSIDE_DIPHOSPHATE_METABOLIC_PRO...,42,
TNNI1,ENSG00000159173.18,4.736913,Ridge 40,NaN,12.0,,,unc-27,Tnni1,TNNI1,TNNI1,"[GOBP_MUSCLE_ORGAN_MORPHOGENESIS, REACTOME_STR...",47,
EEF2,ENSG00000167658.15,4.604556,Ridge 40,NaN,13.0,,EFT1,eef-2,Eef2,EEF2,EEF2,[GOBP_HEMATOPOIETIC_PROGENITOR_CELL_DIFFERENTI...,54,
HBA2,ENSG00000188536.13,4.352626,Ridge 40,NaN,15.0,,,glb-34,Hba-a2,,HBA2,"[GOMF_IRON_ION_BINDING, GOBP_RESPONSE_TO_TOXIC...",45,
MB,ENSG00000198125.12,4.066075,Ridge 40,NaN,17.0,,,glb-34,Mb,MB,MB,"[GOBP_RESPONSE_TO_ABIOTIC_STIMULUS, REACTOME_T...",22,
RPL13A,ENSG00000142541.16,4.014702,Ridge 40,NaN,18.0,,RPL16A,rpl-16,Rpl13a,Symbol not found,RPL13A,"[GOBP_CYTOPLASMIC_TRANSLATION, REACTOME_EUKARY...",87,
KL,ENSG00000133116,17.202229,young.vs.middle,22.416174,3.0,,,klo-1,Kl,KL,KL,"[REACTOME_SIGNALING_BY_FGFR, REACTOME_FRS_MEDI...",104,immune
GPX7,ENSG00000116157,10.084828,middle.vs.old,9.379588,1.0,,,gpx-8,Gpx7,GPX7,GPX7,"[GOBP_CELLULAR_RESPONSE_TO_CHEMICAL_STRESS, GO...",19,
NDUFB4,ENSG00000065518,9.017655,middle.vs.old,9.273909,2.0,,,nuo-6,Ndufb4,NDUFB4,NDUFB4,[REACTOME_THE_CITRIC_ACID_TCA_CYCLE_AND_RESPIR...,61,
KL,ENSG00000133116,14.843816,young.vs.old,14.022549,2.0,,,klo-1,Kl,KL,KL,"[REACTOME_SIGNALING_BY_FGFR, REACTOME_FRS_MEDI...",104,immune
TAF9B,ENSG00000187325,9.848541,young.vs.old,9.571050,5.0,,TAF9,taf-9,Taf9b,TAF9B,TAF9B,"[GOBP_POSITIVE_REGULATION_OF_GROWTH, GOMF_TRAN...",79,
AK1,ENSG00000106992,13.316340,male.vs.female_young,17.697216,1.0,,,F38B2.4,Ak1,,AK1,[GOBP_RIBONUCLEOSIDE_DIPHOSPHATE_METABOLIC_PRO...,51,
GLB1L,ENSG00000163521,12.719610,male.vs.female_young,16.271607,2.0,,,bgal-1,Glb1l,GLB1L,GLB1L,"[REACTOME_KERATAN_SULFATE_KERATIN_METABOLISM, ...",15,
ADA,ENSG00000196839,12.054806,male.vs.female_young,14.462727,5.0,,AAH1,adah-1,Ada,ADA,ADA,"[GOBP_NUCLEOSIDE_CATABOLIC_PROCESS, GOBP_PURIN...",309,immune
AK1,ENSG00000106992,13.316340,male.vs.female_Middle,17.697216,1.0,,,F38B2.4,Ak1,,AK1,[GOBP_RIBONUCLEOSIDE_DIPHOSPHATE_METABOLIC_PRO...,51,
GLB1L,ENSG00000163521,12.719610,male.vs.female_Middle,16.271607,2.0,,,bgal-1,Glb1l,GLB1L,GLB1L,"[REACTOME_KERATAN_SULFATE_KERATIN_METABOLISM, ...",15,
ADA,ENSG00000196839,12.054806,male.vs.female_Middle,14.462727,5.0,,AAH1,adah-1,Ada,ADA,ADA,"[GOBP_NUCLEOSIDE_CATABOLIC_PROCESS, GOBP_PURIN...",309,immune
ERI3,ENSG00000117419,12.552621,male.vs.female_old,43.280851,1.0,,,M02B7.2,Eri3,,ERI3,"[GOBP_RNA_PROCESSING, GOMF_CATALYTIC_ACTIVITY_...",27,
RNF7,ENSG00000114125,11.999396,male.vs.female_old,43.280851,2.0,,,rbx-2,Rnf7l,,RNF7,"[GOMF_NEDD8_TRANSFERASE_ACTIVITY, GOBP_MACROMO...",33,
RECQL,ENSG00000004700,10.074851,male.vs.female_old,15.628665,3.0,,,K02F3.12,Recql,RECQL,RECQL,"[GOMF_HELICASE_ACTIVITY, GOMF_ATP_DEPENDENT_AC...",28,immune
CLIC4,ENSG00000169504,8.623484,male.vs.female_old,22.132263,4.0,,Symbol not found,exc-4,Clic4,CLIC4,CLIC4,[GOBP_CELL_MORPHOGENESIS_INVOLVED_IN_DIFFERENT...,101,
AS3MT,ENSG00000214435,12.164105,young.vs.middle_female,30.988594,5.0,,TMT1,K12D9.1,As3mt,AS3MT,AS3MT,"[REACTOME_PHASE_II_CONJUGATION_OF_COMPOUNDS, G...",13,
CLIC6,ENSG00000159212,14.969741,young.vs.middle_male,20.360480,1.0,,Symbol not found,exc-4,Clic6,,CLIC6,[GOMF_INORGANIC_ANION_TRANSMEMBRANE_TRANSPORTE...,28,
MAST1,ENSG00000105613,13.442936,young.vs.middle_male,19.624840,4.0,,DBF20,kin-4,Mast1,MAST1,MAST1,"[GOCC_CELL_BODY, GOCC_SOMATODENDRITIC_COMPARTM...",22,
CLIC4,ENSG00000169504,12.177729,middle.vs.old_female,22.620990,1.0,,Symbol not found,exc-4,Clic4,CLIC4,CLIC4,[GOBP_CELL_MORPHOGENESIS_INVOLVED_IN_DIFFERENT...,101,
CCNI,ENSG00000118816,9.164860,middle.vs.old_female,20.451636,4.0,,CLB4,cyb-2.2,Ccni,CCNI,CCNI,[GOMF_CYCLIN_DEPENDENT_PROTEIN_SERINE_THREONIN...,31,
MMP23B,ENSG00000189409,8.650188,middle.vs.old_female,19.731339,5.0,MMP23B,,zmp-3,Mmp23,MMP23B,MMP23B,"[GOBP_COLLAGEN_METABOLIC_PROCESS, GOBP_EXTERNA...",15,
AK1,ENSG00000106992,11.010835,middle.vs.old_male,15.704231,3.0,,,F38B2.4,Ak1,,AK1,[GOBP_RIBONUCLEOSIDE_DIPHOSPHATE_METABOLIC_PRO...,51,
CLIC4,ENSG00000169504,12.169155,young.vs.old_female,21.460007,1.0,,Symbol not found,exc-4,Clic4,CLIC4,CLIC4,[GOBP_CELL_MORPHOGENESIS_INVOLVED_IN_DIFFERENT...,101,
CUTC,ENSG00000119929,12.837912,young.vs.old_male,15.214670,3.0,,,cutc-1,Cutc,CUTC,CUTC,"[GOBP_CHEMICAL_HOMEOSTASIS, GOBP_MONOATOMIC_IO...",18,
KLRB1,ENSG00000111796,12.626766,young.vs.old_male,13.015500,4.0,,,clec-146,Klrb1f,KLRB1,KLRB1,"[GOBP_REGULATION_OF_RESPONSE_TO_STRESS, GOBP_R...",29,
MICU1,ENSG00000107745,NaN,Ridge-Catboost-Intersection,NaN,NaN,,,micu-1,Micu1,MICU1,MICU1,"[GOBP_REGULATION_OF_RESPONSE_TO_STRESS, GOBP_C...",59,
PARK7,ENSG00000116288,NaN,Ridge-Catboost-Intersection,NaN,NaN,,SNO4,djr-1.2,Park7,Symbol not found,PARK7,"[GOBP_MAINTENANCE_OF_PROTEIN_LOCATION_IN_CELL,...",514,immune
SBDS,ENSG00000126524,NaN,Ridge-Catboost-Intersection,NaN,NaN,,SDO1,sbds-1,Sbds,SBDS,SBDS,"[GOBP_SPINDLE_ORGANIZATION, GOCC_MICROTUBULE_C...",57,
MEIS2,ENSG00000134138,NaN,Ridge-Catboost-Intersection,NaN,NaN,,,ceh-60,Meis2,MEIS2,MEIS2,"[GOMF_SEQUENCE_SPECIFIC_DNA_BINDING, GOBP_NEGA...",61,
ALDOA,ENSG00000149925,NaN,Ridge-Catboost-Intersection,NaN,NaN,,,aldo-1,Aldoart1,,ALDOA,[GOBP_RIBONUCLEOSIDE_DIPHOSPHATE_METABOLIC_PRO...,103,immune
CA3,ENSG00000164879,NaN,Ridge-Catboost-Intersection,NaN,NaN,,,cah-6,Car3,CA3,CA3,"[GOMF_PHOSPHATASE_ACTIVITY, GOMF_CARBON_OXYGEN...",17,
FEZ2,ENSG00000171055,NaN,Ridge-Catboost-Intersection,NaN,NaN,,,unc-76,Fez2,FEZ2,FEZ2,"[GOBP_TAXIS, GOBP_AUTOPHAGOSOME_ORGANIZATION, ...",35,
EIF3C,ENSG00000184110,NaN,Ridge-Catboost-Intersection,NaN,NaN,,NIP1,eif-3.C,Eif3c,EIF3C,EIF3C,[GOBP_REGULATION_OF_CELLULAR_MACROMOLECULE_BIO...,42,
UBE2H,ENSG00000186591,NaN,Ridge-Catboost-Intersection,NaN,NaN,,UBC8,ubc-8,Ube2h,UBE2H,UBE2H,[GOBP_PROTEIN_MODIFICATION_BY_SMALL_PROTEIN_CO...,23,
CALM1,ENSG00000198668,NaN,Ridge-Catboost-Intersection,NaN,NaN,,,cal-1,Calm1,CALM1,CALM1,"[REACTOME_CALCINEURIN_ACTIVATES_NFAT, GOBP_NEG...",352,immune

In [43]:
gene_df.to_csv("selected_genes_orthologs_c_elegans_pathways.csv")